from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import pymysql
from datetime import datetime

connection = pymysql.connect(host='localhost',port=3306,database='ems',user='root',
                             autocommit=True)
cursor = connection.cursor()

class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1195, 710)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 20, 441, 101))
        self.label.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(600, 30, 561, 71))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 200, 481, 101))
        self.label_3.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(540, 210, 481, 81))
        self.comboBox.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 420, 451, 101))
        self.pushButton.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1191, 671))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(360, 60, 561, 101))
        self.label_4.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 0, 127);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(230, 230, 401, 71))
        self.label_5.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(230, 350, 401, 71))
        self.label_6.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(660, 240, 391, 71))
        self.lineEdit.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(660, 350, 391, 71))
        self.lineEdit_2.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(400, 500, 411, 91))
        self.pushButton_2.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1191, 651))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(170, 30, 241, 71))
        self.label_7.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(450, 30, 621, 71))
        self.label_8.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(100, 130, 481, 61))
        self.label_9.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.radioButton = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton.setGeometry(QtCore.QRect(700, 150, 231, 31))
        self.radioButton.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.radioButton.setObjectName("radioButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(900, 150, 112, 34))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_2)
        self.tableWidget.setGeometry(QtCore.QRect(90, 241, 1001, 391))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1191, 661))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(20, 110, 1151, 511))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(450, 20, 361, 61))
        self.label_10.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 1191, 651))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(390, 10, 341, 71))
        self.label_11.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(240, 110, 261, 41))
        self.label_12.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(590, 100, 431, 51))
        self.lineEdit_3.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(590, 170, 431, 51))
        self.lineEdit_4.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(240, 180, 261, 41))
        self.label_13.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(590, 240, 431, 51))
        self.lineEdit_5.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setGeometry(QtCore.QRect(240, 250, 261, 41))
        self.label_14.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setGeometry(QtCore.QRect(240, 320, 261, 41))
        self.label_15.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_15.setObjectName("label_15")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(590, 380, 431, 51))
        self.lineEdit_7.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(240, 390, 261, 41))
        self.label_16.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_16.setObjectName("label_16")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(590, 450, 431, 51))
        self.lineEdit_8.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_17 = QtWidgets.QLabel(self.frame_4)
        self.label_17.setGeometry(QtCore.QRect(240, 460, 261, 41))
        self.label_17.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_4.setGeometry(QtCore.QRect(390, 540, 451, 71))
        self.pushButton_4.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_4)
        self.comboBox_2.setGeometry(QtCore.QRect(590, 310, 431, 51))
        self.comboBox_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(5, "")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 1191, 651))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_18 = QtWidgets.QLabel(self.frame_5)
        self.label_18.setGeometry(QtCore.QRect(390, 20, 391, 61))
        self.label_18.setStyleSheet("font: 22pt \"MS Shell Dlg 2\";")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_5)
        self.label_19.setGeometry(QtCore.QRect(70, 140, 281, 71))
        self.label_19.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_19.setObjectName("label_19")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_6.setGeometry(QtCore.QRect(370, 140, 371, 71))
        self.lineEdit_6.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_5.setGeometry(QtCore.QRect(800, 140, 351, 71))
        self.pushButton_5.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
        "background-color: rgb(170, 170, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.frame_5)
        self.tableWidget_3.setGeometry(QtCore.QRect(70, 330, 1071, 192))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(5)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 1191, 651))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_20 = QtWidgets.QLabel(self.frame_6)
        self.label_20.setGeometry(QtCore.QRect(490, 20, 211, 71))
        self.label_20.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_6)
        self.label_21.setGeometry(QtCore.QRect(50, 120, 331, 51))
        self.label_21.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_21.setObjectName("label_21")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_9.setGeometry(QtCore.QRect(340, 120, 341, 51))
        self.lineEdit_9.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_6.setGeometry(QtCore.QRect(770, 110, 281, 61))
        self.pushButton_6.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.frame_6)
        self.tableWidget_4.setGeometry(QtCore.QRect(420, 220, 331, 411))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(2)
        self.tableWidget_4.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(5, 0, item)
        self.tableWidget_5 = QtWidgets.QTableWidget(self.frame_6)
        self.tableWidget_5.setGeometry(QtCore.QRect(760, 220, 331, 241))
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(2)
        self.tableWidget_5.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(3, 0, item)
        self.label_22 = QtWidgets.QLabel(self.frame_6)
        self.label_22.setGeometry(QtCore.QRect(780, 470, 161, 41))
        self.label_22.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_6)
        self.label_23.setGeometry(QtCore.QRect(940, 470, 161, 41))
        self.label_23.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.frame_6)
        self.tableWidget_6.setGeometry(QtCore.QRect(40, 220, 371, 411))
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(1)
        self.tableWidget_6.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)

        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 1191, 651))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_24 = QtWidgets.QLabel(self.frame_7)
        self.label_24.setGeometry(QtCore.QRect(290, 120, 311, 71))
        self.label_24.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.label_24.setObjectName("label_24")

        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_10.setGeometry(QtCore.QRect(600, 120, 341, 51))
        self.lineEdit_10.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_7.setGeometry(QtCore.QRect(470, 210, 281, 61))
        self.pushButton_7.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.pushButton_7.setObjectName("pushButton_7")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1195, 31))
        self.menubar.setObjectName("menubar")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuLogin = QtWidgets.QMenu(self.menuOptions)
        self.menuLogin.setObjectName("menuLogin")
        self.menuEmployee = QtWidgets.QMenu(self.menubar)
        self.menuEmployee.setObjectName("menuEmployee")
        self.menuEmp_Salary = QtWidgets.QMenu(self.menubar)
        self.menuEmp_Salary.setObjectName("menuEmp_Salary")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRegister = QtWidgets.QAction(MainWindow)
        self.actionRegister.setObjectName("actionRegister")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAdd_Emp = QtWidgets.QAction(MainWindow)
        self.actionAdd_Emp.setObjectName("actionAdd_Emp")
        self.actionDelete_Emp = QtWidgets.QAction(MainWindow)
        self.actionDelete_Emp.setObjectName("actionDelete_Emp")
        self.actionView_Emp = QtWidgets.QAction(MainWindow)
        self.actionView_Emp.setObjectName("actionView_Emp")
        self.actionUpdate_Emp = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Emp.setObjectName("actionUpdate_Emp")
        self.actionPay_Salary = QtWidgets.QAction(MainWindow)
        self.actionPay_Salary.setObjectName("actionPay_Salary")
        self.actionView_Salary = QtWidgets.QAction(MainWindow)
        self.actionView_Salary.setObjectName("actionView_Salary")
        self.actionUpdate_Salary = QtWidgets.QAction(MainWindow)
        self.actionUpdate_Salary.setObjectName("actionUpdate_Salary")
        self.actionHome = QtWidgets.QAction(MainWindow)
        self.actionHome.setObjectName("actionHome")
        self.actionAs_Employee = QtWidgets.QAction(MainWindow)
        self.actionAs_Employee.setObjectName("actionAs_Employee")
        self.actionAs_Admin = QtWidgets.QAction(MainWindow)
        self.actionAs_Admin.setObjectName("actionAs_Admin")
        self.menuLogin.addAction(self.actionAs_Employee)
        self.menuLogin.addAction(self.actionAs_Admin)
        self.menuOptions.addAction(self.actionHome)
        self.menuOptions.addAction(self.menuLogin.menuAction())
        self.menuOptions.addAction(self.actionQuit)
        self.menuEmployee.addAction(self.actionAdd_Emp)
        self.menuEmployee.addAction(self.actionDelete_Emp)
        self.menuEmployee.addAction(self.actionView_Emp)
        self.menuEmployee.addAction(self.actionUpdate_Emp)
        self.menuEmp_Salary.addAction(self.actionPay_Salary)
        self.menuEmp_Salary.addAction(self.actionView_Salary)
        self.menuEmp_Salary.addAction(self.actionUpdate_Salary)
        self.menubar.addAction(self.menuOptions.menuAction())
        self.menubar.addAction(self.menuEmployee.menuAction())
        self.menubar.addAction(self.menuEmp_Salary.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "AAI Payroll System"))
        self.label_3.setText(_translate("MainWindow", "Login As"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Admin"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Employee"))
        self.pushButton.setText(_translate("MainWindow", "Login Now"))
        self.label_4.setText(_translate("MainWindow", "Login As"))
        self.label_5.setText(_translate("MainWindow", "Login ID"))
        self.label_6.setText(_translate("MainWindow", "Login Password"))
        self.pushButton_2.setText(_translate("MainWindow", "Login"))
        self.label_7.setText(_translate("MainWindow", "Welcome - "))
        self.label_9.setText(_translate("MainWindow", "Mark Today\'s Attendance"))
        self.radioButton.setText(_translate("MainWindow", "Mark"))
        self.pushButton_3.setText(_translate("MainWindow", "Submit"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Leave"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Leave Reason"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Salary Cut"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Emp ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Emp Name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Emp Dept"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Emp Salary"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Emp Address"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Emp Leaves"))
        self.label_10.setText(_translate("MainWindow", "Emoployee\'s Data"))
        self.label_11.setText(_translate("MainWindow", "Register Employee"))
        self.label_12.setText(_translate("MainWindow", "Employee ID"))
        self.label_13.setText(_translate("MainWindow", "Employee Name"))
        self.label_14.setText(_translate("MainWindow", "Employee Password"))
        self.label_15.setText(_translate("MainWindow", "Employee Dept"))
        self.label_16.setText(_translate("MainWindow", "Employee Salary"))
        self.label_17.setText(_translate("MainWindow", "Employee Address"))
        self.pushButton_4.setText(_translate("MainWindow", "Register Employee"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "IT"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "HR"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Sales"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Management"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "R & D"))
        self.label_18.setText(_translate("MainWindow", "Search Employee"))
        self.label_19.setText(_translate("MainWindow", "Enter Emp ID"))
        self.pushButton_5.setText(_translate("MainWindow", "Search"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Emp ID"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Emp Name"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Emp Dept"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Emp Salary"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Emp Address"))
        self.label_20.setText(_translate("MainWindow", "Salary Slip"))
        self.label_21.setText(_translate("MainWindow", "Enter Emp ID"))
        self.pushButton_6.setText(_translate("MainWindow", "Print Slip"))
        item = self.tableWidget_4.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_4.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_4.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_4.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget_4.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Earnings"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Amount"))
        __sortingEnabled = self.tableWidget_4.isSortingEnabled()
        self.tableWidget_4.setSortingEnabled(False)
        item = self.tableWidget_4.item(0, 0)
        item.setText(_translate("MainWindow", "BASIC"))
        item = self.tableWidget_4.item(1, 0)
        item.setText(_translate("MainWindow", "DA"))
        item = self.tableWidget_4.item(2, 0)
        item.setText(_translate("MainWindow", "HRA"))
        item = self.tableWidget_4.item(3, 0)
        item.setText(_translate("MainWindow", "Conv"))
        item = self.tableWidget_4.item(4, 0)
        item.setText(_translate("MainWindow", "Special Allow"))
        item = self.tableWidget_4.item(5, 0)
        item.setText(_translate("MainWindow", "Total"))
        self.tableWidget_4.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget_5.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget_5.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget_5.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Deductions"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Amount"))
        __sortingEnabled = self.tableWidget_5.isSortingEnabled()
        self.tableWidget_5.setSortingEnabled(False)
        item = self.tableWidget_5.item(0, 0)
        item.setText(_translate("MainWindow", "PF"))
        item = self.tableWidget_5.item(1, 0)
        item.setText(_translate("MainWindow", "PT"))
        item = self.tableWidget_5.item(2, 0)
        item.setText(_translate("MainWindow", "TDS"))
        item = self.tableWidget_5.item(3, 0)
        item.setText(_translate("MainWindow", "Total"))
        self.tableWidget_5.setSortingEnabled(__sortingEnabled)
        self.label_22.setText(_translate("MainWindow", "Net Pay"))
        item = self.tableWidget_6.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Emp ID"))
        item = self.tableWidget_6.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Emp Name"))
        item = self.tableWidget_6.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Emp Dept"))
        item = self.tableWidget_6.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Emp Address"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Emp Details"))

        self.label_24.setText(_translate("MainWindow", "Enter Emp ID"))
        self.pushButton_7.setText(_translate("MainWindow", "Delete Emp"))

        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.menuLogin.setTitle(_translate("MainWindow", "Login"))
        self.menuEmployee.setTitle(_translate("MainWindow", "Employee"))
        self.menuEmp_Salary.setTitle(_translate("MainWindow", "Emp Salary"))
        self.actionRegister.setText(_translate("MainWindow", "Register"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAdd_Emp.setText(_translate("MainWindow", "Add Emp"))
        self.actionDelete_Emp.setText(_translate("MainWindow", "Delete Emp"))
        self.actionView_Emp.setText(_translate("MainWindow", "Search Emp"))
        self.actionUpdate_Emp.setText(_translate("MainWindow", "Update Emp"))
        self.actionPay_Salary.setText(_translate("MainWindow", "Pay Salary"))
        self.actionView_Salary.setText(_translate("MainWindow", "View Salary"))
        self.actionUpdate_Salary.setText(_translate("MainWindow", "Update Salary"))
        self.actionHome.setText(_translate("MainWindow", "Home"))
        self.actionAs_Employee.setText(_translate("MainWindow", "As Employee"))

        self.actionAs_Admin.setText(_translate("MainWindow", "As Admin"))

        self.menuOptions.setDisabled(True)
        self.menuEmployee.setDisabled(True)
        self.menuEmp_Salary.setDisabled(True)
        self.actionAdd_Emp.triggered.connect(self.registerEmpScreen)
        self.actionPay_Salary.triggered.connect(self.paySalaryScreen)

        self.frame.hide()
        self.pushButton.clicked.connect(self.showLogin)
        self.pushButton_2.clicked.connect(self.login)
        self.pushButton_3.clicked.connect(self.markAttendance)
        self.pushButton_4.clicked.connect(self.registerEmp)
        self.pushButton_6.clicked.connect(self.paySalary)

    def registerEmpScreen(self):
        self.frame_4.show()
        self.frame_5.hide()

    def paySalaryScreen(self):
        self.frame_3.show()
        self.frame_4.show()
        self.frame_5.show()
        self.frame_6.show()
        self.frame_7.hide()
        self.paySalary()

    def showLogin(self):
        self.frame.show()
        self.frame_2.hide()
        self.loginAs = self.comboBox.currentText()
        self.label_4.setText("Login As {}".format(self.loginAs))

    def paySalary(self):
        try:
            login_id = self.lineEdit_9.text()
            item = QtWidgets.QTableWidgetItem()
            query = "select * from employees where emp_id= %s "
            cursor.execute(query, (login_id))
            emp_n = cursor.fetchall()
            print(emp_n)
            self.tableWidget_6.setItem(1, 0, item)
            item.setText(emp_n[0][1])
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_6.setItem(2, 0, item)
            item.setText(emp_n[0][3])
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_6.setItem(3, 0, item)
            item.setText("Delhi")
            item = QtWidgets.QTableWidgetItem()
            query_1 = "select * from sal where emp_id = %s"
            cursor.execute(query_1,(login_id))
            salary = cursor.fetchall()
            print(salary)
            self.tableWidget_4.setItem(0, 1, item)
            item.setText(str(salary[0][1]))
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_4.setItem(1, 1, item)
            item.setText(str(salary[0][2]))
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_4.setItem(2, 1, item)
            item.setText(str(salary[0][3]))
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_4.setItem(3, 1, item)
            item.setText(str(salary[0][4]))
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_4.setItem(4, 1, item)
            item.setText(str(salary[0][5]))
            total = salary[0][1]+salary[0][2]+salary[0][3]+salary[0][4]+salary[0][5]
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_4.setItem(5, 1, item)
            item.setText(str(total))
            item = QtWidgets.QTableWidgetItem()
            query_2 = "select * from pf where emp_id = %s"
            cursor.execute(query_2, (login_id))
            pf = cursor.fetchall()
            print(pf)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_5.setItem(0, 1, item)
            item.setText(str(pf[0][1]))
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_5.setItem(1, 1, item)
            item.setText(str(pf[0][2]))
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_5.setItem(2,1 , item)
            item.setText(str(pf[0][3]))
            total_1 = pf[0][1]+pf[0][2]+pf[0][3]
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget_5.setItem(3,1, item)
            item.setText(str(total_1))
            netpay = total - total_1
            self.label_23.setText(str(netpay))

        except BaseException as ex:
            print(ex)

    def login(self):
        login_id = self.lineEdit.text()
        login_pwd = self.lineEdit_2.text()
        if self.loginAs == "Admin":
            if login_id == "admin" and login_pwd == "aai_admin":
                self.loginAdmin()
        else:
            query = "select * from employees where emp_id = %s and emp_pwd = %s"
            cursor.execute(query, (login_id, login_pwd))
            emp = cursor.fetchall()
            if(len(emp)) < 1:
                QMessageBox.about(self,'login fail','Invalid Id or Pwd')
            else:
                self.loginEmp(emp)

    def loginAdmin(self):
        self.frame_2.show()
        self.frame_4.hide()
        self.menuOptions.setDisabled(False)
        self.menuEmployee.setDisabled(False)
        self.menuEmp_Salary.setDisabled(False)
        self.showAllEmp()

    def loginEmp(self,data):
        self.frame_2.show()
        self.frame_3.hide()
        self.emp_id = data[0][0]
        self.label_8.setText(data[0][1])
        try:
            query = "select date,emp_leave,leave_reason,salary_cut from emp_attendance where emp_id = %s"
            cursor.execute(query,(self.emp_id))
            data = cursor.fetchall()
            row_count = cursor.rowcount
            col_count = len(data[0])
            self.tableWidget.setColumnCount(col_count)
            self.tableWidget.setRowCount(row_count)
            for i in range(row_count):
                for j in range(col_count):
                    item = QtWidgets.QTableWidgetItem()
                    self.tableWidget.setItem(i, j, item)
                    item.setText(str(data[i][j]))
        except BaseException as ex:
            print(ex)


    def markAttendance(self):
        try:
            cur_date = datetime.now().date()
            cur_date = cur_date.strftime("%y-%m-%d")
            query = "insert into emp_attendance values (%s, %s, %s, %s,%s)"
            leave = "no"
            reason = ""
            if leave == "no":
                salarycut = 0
            else:
                salarycut = 1000
            cursor.execute(query, (cur_date,leave,reason,salarycut,self.emp_id))
            QMessageBox.about(self,'success','marked')
        except BaseException as ex:
            print(ex)


    def showAllEmp(self):
        try:
            query = "select emp_id, emp_name, emp_dept, emp_sal, emp_address from employees"
            cursor.execute(query)
            data = cursor.fetchall()
            data = list(data)
            row_count = cursor.rowcount

            query2 = "SELECT emp_id, COUNT(emp_leave) FROM emp_attendance WHERE emp_leave = 'yes' GROUP BY emp_id"
            cursor.execute(query2)
            leave_count = cursor.fetchall()

            for i in range(row_count):
                for j in range(len(leave_count)):
                    if data[i][0] == leave_count[j][0]:
                        data[i] = list(data[i])
                        data[i].append(leave_count[j][1])

            col_count = len(data[0])
            self.tableWidget_2.setColumnCount(col_count)
            self.tableWidget_2.setRowCount(row_count)
            for i in range(row_count):
                for j in range(col_count):
                    item = QtWidgets.QTableWidgetItem()
                    self.tableWidget_2.setItem(i, j, item)
                    item.setText(str(data[i][j]))
        except BaseException as ex:
            print(ex)

    def registerEmp(self):
        try:
            emp_id = self.lineEdit_3.text()
            emp_name = self.lineEdit_4.text()
            emp_pwd = self.lineEdit_5.text()
            emp_dept = self.comboBox_2.currentText()
            emp_sal = self.lineEdit_7.text()
            emp_address = self.lineEdit_8.text()

            query = "insert into employees values (%s,%s,%s,%s,%s,%s)"
            cursor.execute(query,(emp_id, emp_name, emp_pwd, emp_dept, emp_sal, emp_address))
            QMessageBox.about(self,"Success","Data Inserted")
            self.loginAdmin()
        except BaseException as ex:
            print(ex)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
